# Generated by Django 5.2.1 on 2025-05-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_remove_order_products_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
