# Generated by Django 5.2.1 on 2025-05-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_rename_product_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
