# Generated by Django 5.2.1 on 2025-05-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shopapp.product'),
        ),
    ]
