# Generated by Django 5.2.1 on 2025-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shopapp.client'),
        ),
    ]
