# Generated by Django 5.2.1 on 2025-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_remove_order_client_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shopapp.client'),
        ),
    ]
