# Generated by Django 5.2.1 on 2025-05-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0017_order_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', 'client'), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
