# Generated by Django 5.2.1 on 2025-05-26 18:04

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0019_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.product_images_directory_path),
        ),
    ]
