# Generated by Django 5.2.1 on 2025-05-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0021_alter_product_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='picture',
        ),
    ]
