# Generated by Django 5.2.1 on 2025-05-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0022_rename_preview_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='picture',
        ),
    ]
