# Generated by Django 5.2.1 on 2025-05-27 19:44

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0023_rename_image_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=1, upload_to=shopapp.models.product_preview_directory_path),
            preserve_default=False,
        ),
    ]
