# Generated by Django 5.2.1 on 2025-05-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0025_alter_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='pinture',
        ),
    ]
