# Generated by Django 5.2.1 on 2025-05-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0026_rename_picture_product_pinture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pinture',
            new_name='picture',
        ),
    ]
